version: '3.9'

services:
  db:
    image: mysql:8.0.34
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env  # Include the .env file here for the db service
    volumes:
      - ./mysqldb_todo:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_ARBITRARY: 1

volumes:
  mysqldb_todo: